//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocabulate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vocabulate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1872_Expression_F1142_fig18 {
            get {
                object obj = ResourceManager.GetObject("_1872_Expression_F1142_fig18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `
        ///~
        ///!
        ///@
        ///#
        ///$
        ///%
        ///^
        ///&amp;
        ///*
        ///(
        ///)
        ///_
        ///+
        ///-
        ///=
        ///[
        ///]
        ///\
        ///;
        ///&apos;
        ///,
        ///.
        ////
        ///{
        ///}
        ///|
        ///:
        ///&quot;
        ///&lt;
        ///&gt;
        ///?
        ///..
        ///...
        ///«
        ///««
        ///»»
        ///“
        ///”
        ///‘
        ///‘‘
        ///’
        ///’’
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///0
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///19
        ///20
        ///25
        ///30
        ///33
        ///40
        ///50
        ///60
        ///66
        ///70
        ///75
        ///80
        ///90
        ///99
        ///100
        ///123
        ///1000
        ///10000
        ///12345
        ///100000
        ///1000000.
        /// </summary>
        internal static string StopListCharacters {
            get {
                return ResourceManager.GetString("StopListCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///about
        ///above
        ///absolutely
        ///across
        ///actually
        ///after
        ///again
        ///against
        ///ahead
        ///aint
        ///ain&apos;t
        ///all
        ///allot
        ///along
        ///alot
        ///also
        ///although
        ///am
        ///among
        ///amongst
        ///an
        ///and
        ///another
        ///any
        ///anybodies
        ///anybody
        ///anybody&apos;s
        ///anymore
        ///anyone
        ///anyone&apos;s
        ///anything
        ///anyway
        ///anyways
        ///anywhere
        ///apparently
        ///are
        ///arent
        ///aren&apos;t
        ///around
        ///as
        ///at
        ///atho
        ///atop
        ///away
        ///back
        ///basically
        ///be
        ///became
        ///because
        ///become
        ///becomes
        ///becoming
        ///been
        ///before
        ///behind
        ///being
        ///below
        ///beneath
        ///beside
        ///besides
        ///best
        ///between
        ///beyond
        ///billion
        ///billions
        ///billiont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StopListEN {
            get {
                return ResourceManager.GetString("StopListEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon vocab {
            get {
                object obj = ResourceManager.GetObject("vocab", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
